apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secret.yaml
images:
- name: daizf/flask-demo
  newTag: 24d454f9197b7da56614231428a3d7c19c021c23
